### ISSUE TITLE
ESRC: Inform sowing pilot when cache involved in rescue

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#176] opened 2018-01-14 15:17 UTC
- Inform sowing pilot when cache involved in rescue

**Comment by Thricehappy** [comment] 2018-08-22 20:31
Also inform all tenders, etc.

**Comment by adeadparrot** [comment] 2020-06-28 13:02
duplicate of #231

**Closed by adeadparrot** 2020-06-28 13:02 UTC
Labels: enhancement
