### ISSUE TITLE
SAR Locate Payout Shows 0 ISK for the Locator in Firefox

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#320] opened 2020-08-12 20:23 UTC
<img width="365" alt="Screen Shot 2020-08-12 at 2 22 57 PM" src="https://user-images.githubusercontent.com/2007040/90064037-6deb2e80-dca7-11ea-952d-c984fba96548.png">

**Comment by Thricehappy** [comment] 2020-08-12 23:49
Is this Firefox-only or broken in Chrome, too?

**Comment by Thricehappy** [comment] 2020-08-13 17:55
This was being caused by the check to see whether a given pilot is an "ESR Coordinator." Those who are, receive 0 payout. In some cases, the check was returning the status of the logged-in user instead of the requested user. Firefox may handle session variables slightly differently than Chrome, which was causing the discrepancy between results based on browser.

Tested and confirmed working correctly on both Chrome and Firefox now. No other browser tested, but the fix I made to Users->isSARCoordinator() should prevent this from occurring, regardless of context.

**Comment by chigaze** [comment] 2020-08-13 18:00
The manager group had been discussing eliminating the coordinator exclusion as it does not make as much sense anymore. The reality is most of our advantage we've handed to the Operators by feeding them chains. Any future exclusions could be handled in the opt-out system you put together.

**Comment by Thricehappy** [comment] 2020-08-13 18:01
If you need the current exclusion modified or removed, please open a new issue for that. I will be closing this one out shortly. Thanks!

**Closed** 2020-08-13 18:02 UTC
Labels: bug
