### ISSUE TITLE
Add statics to WH info on system-specific display

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#193] opened 2018-04-10 12:50 UTC
Can we get the system's Statics listed on the detail page as well? For example, pulling up the page for a search in J222914 would show it's a c1 with a Nullsec connection
- Triffton Ambraelle

**Comment by Thricehappy** [comment] 2018-07-20 16:48
Merge [mapWormholes] from dev into [wh_systems] table so we can display static connections for each WH.

**Comment by Klensor** [comment] 2019-06-24 06:40
duplicate of #212

**Closed** 2019-09-17 11:48 UTC
Labels: duplicate
